
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnawqepohegfcxychvbg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJuYXdxZXBvaGVnZmN4eWNodmJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxOTY1ODUsImV4cCI6MjA1OTc3MjU4NX0.OSUzyU7OoqFMopjKQOHZ71YeWyRwXZ21Wc_HEWm4U20";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
